import { createContext, useContext, useEffect, useState } from 'react';
import { conversations as seedConversations, documents as seedDocuments, initialNotifications, initialReminders, initialTasks } from '../data/mockData';
const AppContext = createContext(null);
const fromStore = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
export function AppProvider({ children }) {
  const [documents, setDocuments] = useState(() => fromStore('la_documents', seedDocuments));
  const [tasks, setTasks] = useState(() => fromStore('la_tasks', initialTasks));
  const [reminders, setReminders] = useState(() => fromStore('la_reminders', initialReminders));
  const [notifications, setNotifications] = useState(() => fromStore('la_notifications', initialNotifications));
  const [conversations, setConversations] = useState(() => fromStore('la_conversations', seedConversations));
  const [authenticated, setAuthenticated] = useState(() => localStorage.getItem('la_auth') === 'true');
  const [theme, setTheme] = useState(() => localStorage.getItem('la_theme') || 'light');
  const [toast, setToast] = useState('');
  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2600); };
  useEffect(() => localStorage.setItem('la_documents', JSON.stringify(documents)), [documents]);
  useEffect(() => localStorage.setItem('la_tasks', JSON.stringify(tasks)), [tasks]);
  useEffect(() => localStorage.setItem('la_reminders', JSON.stringify(reminders)), [reminders]);
  useEffect(() => localStorage.setItem('la_notifications', JSON.stringify(notifications)), [notifications]);
  useEffect(() => localStorage.setItem('la_conversations', JSON.stringify(conversations)), [conversations]);
  useEffect(() => { localStorage.setItem('la_theme', theme); const media = window.matchMedia('(prefers-color-scheme: dark)'); const apply = () => document.documentElement.classList.toggle('dark', theme === 'dark' || (theme === 'system' && media.matches)); apply(); media.addEventListener('change', apply); return () => media.removeEventListener('change', apply); }, [theme]);
  const login = () => { localStorage.setItem('la_auth', 'true'); setAuthenticated(true); };
  const logout = () => { localStorage.removeItem('la_auth'); setAuthenticated(false); };
  const addDocument = (doc) => { setDocuments((v) => [doc, ...v]); return doc; };
  const updateDocument = (id, values) => setDocuments((v) => v.map((d) => d.id === id ? { ...d, ...values } : d));
  const deleteDocument = (id) => { setDocuments((v) => v.filter((d) => d.id !== id)); setTasks((v) => v.filter((t) => t.source !== id && t.sourceDocumentId !== id)); setReminders((v) => v.filter((r) => r.source !== id && r.sourceDocumentId !== id)); };
  const completeTask = (id) => { setTasks((v) => v.map((t) => t.id === id ? { ...t, status: t.status === 'Completed' ? 'Pending' : 'Completed' } : t)); notify('Task updated'); };
  const deleteTask = (id) => { setTasks((v) => v.filter((t) => t.id !== id)); notify('Task deleted'); };
  const snoozeTask = (id) => { setTasks((v) => v.map((t) => t.id === id ? { ...t, due: 'Snoozed until tomorrow' } : t)); notify('Task snoozed'); };
  return <AppContext.Provider value={{ documents, setDocuments, addDocument, updateDocument, deleteDocument, tasks, setTasks, reminders, setReminders, notifications, setNotifications, conversations, setConversations, authenticated, login, logout, theme, setTheme, toast, notify, completeTask, deleteTask, snoozeTask }}>{children}</AppContext.Provider>;
}
export const useApp = () => useContext(AppContext);
