import 'dotenv/config';
import assert from 'node:assert/strict';
import mongoose from 'mongoose';
import { randomUUID } from 'node:crypto';
import app from '../app.js';
import { connectDB } from '../config/db.js';
import User from '../models/User.js';
import Task from '../models/Task.js';
import Document from '../models/Document.js';
import DocumentChunk from '../models/DocumentChunk.js';
import CalendarEvent from '../models/CalendarEvent.js';
import AvailabilityProfile from '../models/AvailabilityProfile.js';
import Conversation from '../models/Conversation.js';
import WorkspaceChatMessage from '../models/WorkspaceChatMessage.js';
import { answerWorkspaceQuestion, classifyAssistantIntent } from '../services/assistantService.js';
import { retrieveWorkspace } from '../services/workspaceRetrievalService.js';
import { generateText } from '../services/ai/aiService.js';
import { setWorkspaceAnswererForTests } from '../controllers/assistantController.js';
import { collectBriefingData, briefingClock } from '../services/dailyBriefingService.js';
const live = process.argv.includes('--live');
const liveGenerate = async args => { for(let attempt=0;attempt<3;attempt++){try{return await generateText(args);}catch(error){if(error.code!=='AI_RATE_LIMITED'||attempt===2)throw error;console.log('Provider rate limit; waiting before live verification retry.');await new Promise(resolve=>setTimeout(resolve,35000));}} };
let server, userId;
const check = (value, label) => { assert.ok(value, label); console.log(`PASS ${label}`); };
try {
 await connectDB(); server = app.listen(0); await new Promise(resolve => server.once('listening', resolve));
 const api = async (route, method = 'GET', body, token) => { const r = await fetch(`http://127.0.0.1:${server.address().port}/api${route}`, { method, headers: { 'content-type':'application/json', ...(token ? { authorization:`Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { status: r.status, ...await r.json() }; };
 const email = `${randomUUID()}@hardening-test.local`, password = 'Hardening123';
 const account = await api('/auth/register','POST',{fullName:'Hardening Test',email,password}); userId=account.user._id;
 const req = (route, method, body) => api(route, method, body, account.token);
 const doc = await Document.create({userId,title:'Cryptography Assignment',sourceType:'text',extractedText:'Assignment requirement: compare CBC (Cipher Block Chaining) and CTR (Counter) modes for AES. Include a two-block CBC worked example. Discuss IV requirements, padding, parallelism and confidentiality versus integrity.'});
 const selectedChat = (await req('/conversations','POST',{type:'global'})).conversation;
 check((await req(`/conversations/${selectedChat._id}`,'PATCH',{documentId:String(doc._id)})).status===200,'Document selection is saved on the existing conversation');
 check(String((await req(`/conversations/${selectedChat._id}`)).conversation.documentId)===String(doc._id),'Reload preserves selected document');
 check((await req(`/conversations/${selectedChat._id}`,'PATCH',{documentId:new mongoose.Types.ObjectId().toString()})).status===404,'Invalid document selection is rejected');
 setWorkspaceAnswererForTests(args => answerWorkspaceQuestion({...args,generate: async prompt => { assert.match(prompt.userPrompt,/two-block CBC worked example/); return {text:'CBC explanation based on the assignment.'}; }}));
 const selectedAnswer = await req(`/conversations/${selectedChat._id}/messages`,'POST',{message:'Explain CBC mode.',requestId:randomUUID()});
 check(selectedAnswer.status===201 && selectedAnswer.sources.some(s=>String(s.sourceId)===String(doc._id)),'Selected document reaches existing assistant and RAG pipeline');
 await req(`/conversations/${selectedChat._id}`,'PATCH',{documentId:null});
 let reads=0, retrievalCalls=0, providerCalls=0;
 mongoose.set('debug', (_c,method)=> {if(['find','findOne','aggregate','countDocuments'].includes(method)) reads++;});
 const general = await answerWorkspaceQuestion({userId,message:'What is CBC mode?',retrieve:()=>{throw Error('Unexpected workspace retrieval');},generate:async args=>{providerCalls++;return live?liveGenerate(args):{text:'## CBC\nCipher Block Chaining uses an unpredictable IV and XOR with the previous ciphertext block. Encryption alone does not authenticate messages.'};}});
 check(reads===0 && providerCalls===1 && /Cipher Block Chaining/i.test(general.answer), 'A: CBC uses provider knowledge with zero workspace MongoDB reads');
 mongoose.set('debug',false);
 for(const message of ['Where can I buy a cricket bat?','Give me physical shops where I can buy a cricket bat.','Explain photosynthesis.','What is the capital of Australia?']) {
   let queried=false;
   const result=await answerWorkspaceQuestion({userId,message,history:[{role:'assistant',content:'I could not find this information in the document.',sources:[{type:'document',sourceId:doc._id}]}],retrieve:()=>{queried=true;throw Error('Unexpected retrieval');},generate:async()=>({text:'General knowledge answer.'})});
   check(!queried && !result.sources.length && result.providerCall,'General route remains independent after document history: '+message);
 }
 const hybrid = await answerWorkspaceQuestion({userId,message:'Explain CBC based on my assignment.',retrieve:async args=>{retrievalCalls++;return retrieveWorkspace(args);},generate:async args=>{assert.match(args.userPrompt,/two-block CBC worked example/);return live?liveGenerate(args):{text:'## Assignment context\nCompare CBC and CTR.\n## Explanation\nCBC chains blocks using XOR.'};}});
 check(classifyAssistantIntent('Explain CBC based on my assignment.').intent==='hybrid' && retrievalCalls===1 && hybrid.sources.some(s=>String(s.sourceId)===String(doc._id)), 'C: Assignment explanation receives document excerpts and preserves sources');
 if(live){console.log('LIVE CBC ANSWER\n'+general.answer);console.log('LIVE HYBRID ANSWER\n'+hybrid.answer);const ctr=await answerWorkspaceQuestion({userId,message:'Compare CBC and CTR modes.',generate:liveGenerate});console.log('LIVE COMPARISON\n'+ctr.answer);}
 const task=(await req('/tasks','POST',{title:'Finish cryptography assignment',dueDate:new Date().toISOString(),priorityOverride:'high'})).task;
 const before=await answerWorkspaceQuestion({userId,message:'What should I focus on today?'});
 check(before.sources.some(s=>String(s.sourceId)===task._id),'B: Focus includes current pending task');
 await req('/schedule/availability','PUT',{timezone:'UTC',workingDays:[0,1,2,3,4,5,6],availableTimeRanges:[{start:'00:00',end:'23:59'}]});
 const blocks=await CalendarEvent.create([0,1].map(i=>({userId,relatedTaskId:task._id,title:task.title,type:'task_block',startTime:new Date(Date.now()+i*3600000),endTime:new Date(Date.now()+(i+1)*3600000)})));
 check((await req(`/schedule/events/${blocks[0]._id}`,'PATCH',{status:'completed'})).status===200,'D: Calendar completion succeeds');
 check((await req(`/tasks/${task._id}`)).task.status==='completed','D: Real Task record is completed');
 check(await CalendarEvent.countDocuments({userId,relatedTaskId:task._id,status:'completed'})===2,'D: All linked blocks reflect completed Task');
 const dashboard=await req('/dashboard');
 check(dashboard.taskProgress.completed===1 && !dashboard.todaysFocus.some(t=>String(t._id)===task._id),'D: Dashboard completion count and focus are current');
 const briefing=await collectBriefingData(userId,briefingClock(new Date(),'UTC'));
 check(briefing.counts.openTasks===0 && briefing.counts.overdue===0 && !briefing.focusTasks.length && !briefing.upcomingEvents.some(item=>String(item.sourceId)===task._id),'Daily Briefing excludes completed task from focus, open, overdue and upcoming work');
 const focus=await answerWorkspaceQuestion({userId,message:'What should I focus on today?',history:[{role:'assistant',content:before.answer,sources:before.sources}]});
 check(!focus.answer.includes(task.title) && !focus.sources.some(s=>String(s.sourceId)===task._id),'D: Ask does not recommend completed task from old history');
 check((await req(`/tasks/${task._id}`,'PATCH',{status:'pending'})).status===200,'Reopening Task succeeds');
 check(await CalendarEvent.countDocuments({userId,relatedTaskId:task._id,status:'planned'})===2,'Reopening restores Calendar state');
 await req(`/tasks/${task._id}`,'PATCH',{status:'completed'});
 check(await CalendarEvent.countDocuments({userId,relatedTaskId:task._id,status:'completed'})===2,'E: Tasks completion updates Calendar');
 const login=await api('/auth/login','POST',{email,password});
 check((await api(`/tasks/${task._id}`,'GET',null,login.token)).task.status==='completed','F: Fresh login and API refresh preserve completion');
 console.log('Hardening runtime checks complete.');
} catch(error){console.error(error.code || error.message);process.exitCode=1;} finally { mongoose.set('debug',false); if(server)await new Promise(resolve=>server.close(resolve)); if(userId)for(const Model of [CalendarEvent,AvailabilityProfile,Task,DocumentChunk,Document,WorkspaceChatMessage,Conversation,User])await Model.deleteMany(Model===User?{_id:userId}:{userId});await mongoose.disconnect(); }
